Epoll.o:Epoll.h Epoll.cpp SocketAddress.o TCPSocket.o
	g++ -g -c Epoll.cpp

SocketAddress.o:SocketAddress.h SocketAddress.cpp
	g++ -g -c SocketAddress.cpp

TCPSocket.o: TCPSocket.h TCPSocket.cpp
	g++ -g -c TCPSocket.cpp


